#! /usr/bin/perl

=pod

=head1 NAME

B<squid_logview>

=head1 DESCRIPTION

View default squid access log converting date from secs to a human form

=head1 SYNOPSIS

B<squid_logview> /var/log/squid/access.log

B<squid_logview> /var/log/squid/access.log.1.gz

tail /var/log/squid/access.log | B<squid_logview>

=cut

#use IO::Handle;
use IO::File;

$GUNZIP='/bin/gunzip';
sub usage {
 print "@_\n" if @_;
 print qq|
 Usare: $0 [file_squid_log]
  file_squid_log may be compressed in .gz (file_squid_log.gz).
  You may use this as a filter reading to the standard input
 |;
 exit 1;
}

# usage() if ! $ARGV[0];
usage() if $ARGV[0] && ! -e $ARGV[0];
$fh = new IO::Handle;
if ($ARGV[0]=~/\.gz$/) {
 $fh = new IO::File("$GUNZIP -c $ARGV[0] |") or usage("ERR: ($GUNZIP | $ARGV[0]) $!")
 # open (F, "$GUNZIP | $ARGV[0]") or usage($!);
}
elsif($ARGV[0]) {
 $fh = new IO::File($ARGV[0]) or usage($!);
 # open (F,$ARGV[0]) or usage($!);
}
else {
 $fh->fdopen(fileno(STDIN),"r") or usage($!);
}
while ($log=<$fh>) {$log=~s/^\d+\.\d+/localtime $&/e; print $log;}
close F;
exit;

=head1 COPYRIGHT

squid_logview is Copyright (c) 2014 Enio Carboni - Italy
squid_logview is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
squid_logview is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.
You should have received a copy of the GNU General Public License
along with offline. If not, see <http://www.gnu.org/licenses/>.

=head1 SUPPORT / WARRANTY

The squid_logview is free Open Source software. IT COMES WITHOUT WARRANTY OF ANY KIND.
